-- MySQL Script generated by MySQL Workbench
-- Wed May  5 20:06:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

use streamzer;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Movie` (
  `id` BIGINT NOT NULL COMMENT 'Primary Key - Identifier',
  `name` VARCHAR(150) NOT NULL COMMENT 'Name of the movie',
  `description` TEXT NULL COMMENT 'Synopsis\n',
  `author` VARCHAR(100) NULL COMMENT 'Author\'s fullname',
  `date_release` DATE NULL COMMENT 'Release date\n\n',
  `picture` VARCHAR(100) NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `id` BIGINT NOT NULL COMMENT 'Primary Key - Identifier',
  `name` VARCHAR(150) NOT NULL COMMENT 'Name of category',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Serie` (
  `id` BIGINT NOT NULL COMMENT 'Primary Key - Identifier',
  `name` VARCHAR(150) NOT NULL COMMENT 'Name of the serie\n',
  `description` TEXT NULL COMMENT 'Synopsis\n',
  `author` VARCHAR(100) NULL COMMENT 'Author\'s fullname\n',
  `date_release` DATE NULL COMMENT 'Release date of the serie\n\n',
  `picture` VARCHAR(100) NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Season` (
  `id` BIGINT NOT NULL COMMENT 'Primary Key - Identifier',
  `number` INT NOT NULL COMMENT 'Season\'s number',
  `serie_id` BIGINT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Season_Serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_Season_Serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `Serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `is_admin` TINYINT NULL DEFAULT 0,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Episode` (
  `id` BIGINT NOT NULL COMMENT 'Primary Key - Identifier',
  `number` INT NOT NULL COMMENT 'Name of the serie\n',
  `season_id` BIGINT NOT NULL,
  `serie_id` BIGINT NOT NULL,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Movies_Season_idx` (`season_id` ASC),
  INDEX `fk_Episode_Serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_Movies_Season00`
    FOREIGN KEY (`season_id`)
    REFERENCES `Season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Episode_Serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `Serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieCategory` (
  `movie_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`movie_id`, `category_id`),
  INDEX `fk_Movie_has_Category_Category1_idx` (`category_id` ASC),
  INDEX `fk_Movie_has_Category_Movie1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_Movie_has_Category_Movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Category_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SerieCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SerieCategory` (
  `serie_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`serie_id`, `category_id`),
  INDEX `fk_Serie_has_Category_Category1_idx` (`category_id` ASC),
  INDEX `fk_Serie_has_Category_Serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_Serie_has_Category_Serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `Serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serie_has_Category_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
